# version: "3.9"

networks:
  expense: {}

volumes:
  mysql: {}

services:
  mysql:
    build: ./mysql
    image: mysql:1.0.0
    container_name: mysql
    networks:
      - expense
    volumes:
      - mysql:/var/lib/mysql

  backend:
    build: ./backend
    image: backend:1.0.0
    container_name: backend
    networks:
      - expense
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    image: frontend:1.0.0
    container_name: frontend
    networks:
      - expense
    ports:
      - "80:80"
    depends_on:
      - backend