apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-uat
  labels:
    app: backend
    tier: backend
    purpose: expense-uat

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend
      tier: backend
      purpose: expense-uat

  template:
    metadata:
      labels:
        app: backend
        tier: backend
        purpose: expense-uat

    spec:
      containers:
      - name: backend
        image: balumopuri19/backend.1.0.0