apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense-app
    component: backend
    version: "1.0.0"
    environment: dev
    demo: lb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodeport }}