apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::652942058685:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-z1ztxcGL0sJi
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::315069654700:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-17T09:11:45Z"
  name: aws-auth
  namespace: kube-system
  uid: 917eb0b0-ab32-48b6-a4ed-058ab841f675