# FROM node:20-bullseye-slim AS builder
FROM node:20.18.3-alpine3.21
# RUN apt-get update && apt-get install -y telnet && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/backend
COPY package.json .
COPY *.js .
RUN npm install
ENV DB_HOST="mysql"
CMD ["node","index.js"]
