# FROM node:20
FROM node:20.18.3-alpine3.21 AS builder
RUN apt-get update && apt-get install -y telnet && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/backend
COPY package.json .
COPY *.js .
RUN npm install
ENV DB_HOST="mysql"
CMD ["node","index.js"]
