- name: variables
  hosts: local
  connection: local
  vars:                          # Play level variables
    COURSE: Devops with AWS
    DURATION: 3 months
    TRAINER: Siva
  tasks:
    - name: print the value of variables
      vars:                      # Task level variables
        COURSE: Ansible for Beginners
        DURATION: 2 months
      ansible.builtin.debug:
        msg: "{{ COURSE }} - {{ DURATION }} - {{ TRAINER }}"

    - name: print the variable1
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"